spring:
  datasource:
    url: jdbc:mysql://localhost/paymybuddy?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: openclassrooms
    password: AAAAbbbb1234
    driver-class-name: com.mysql.cj.jdbc.Driver