spring:
  profile: test
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: test
    password: ENC(sdjxanhFVDz3W8IKXPw/bw==)
  logging:
    level:
      org:
        hibernate:
          type: trace
  h2:
    console:
      enabled: true
jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES