spring:
  profile: test
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: test
    password: test
  logging:
    level:
      org:
        hibernate:
          type: trace
  h2:
    console:
      enabled: true